# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/mini_UAL_full_adder_4B_0_0.xci
# IP: The module: 'mini_UAL_full_adder_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/full_adder_4B_full_add_1B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_0_0 || ORIG_REF_NAME==full_adder_4B_full_add_1B_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/full_adder_4B_full_add_1B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_0 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/full_adder_4B_full_add_1B_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_1 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/full_adder_4B_full_add_1B_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_2 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_nor4_0_0/full_adder_4B_xup_nor4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_nor4_0_0 || ORIG_REF_NAME==full_adder_4B_xup_nor4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_0/full_adder_4B_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_1/full_adder_4B_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_1 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_2/full_adder_4B_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_2 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_3/full_adder_4B_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_3 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ATAD_SPLIT_4_0_0/full_adder_4B_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ATAD_SPLIT_4_0_1/full_adder_4B_ATAD_SPLIT_4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_1 || ORIG_REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xlconcat_0_0/full_adder_4B_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xlconcat_0_0 || ORIG_REF_NAME==full_adder_4B_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_4_0/full_adder_4B_xup_xor2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_4_0 || ORIG_REF_NAME==full_adder_4B_xup_xor2_4_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mini_UAL_full_adder_4B_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_ooc.xdc

# IP: D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/mini_UAL_full_adder_4B_0_0.xci
# IP: The module: 'mini_UAL_full_adder_4B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/full_adder_4B_full_add_1B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_0_0 || ORIG_REF_NAME==full_adder_4B_full_add_1B_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/full_adder_4B_full_add_1B_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_0 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/full_adder_4B_full_add_1B_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_1 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/full_adder_4B_full_add_1B_1_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_full_add_1B_1_2 || ORIG_REF_NAME==full_adder_4B_full_add_1B_1_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_1_1/full_add_1B_xup_and2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_1_1 || ORIG_REF_NAME==full_add_1B_xup_and2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_2_1/full_add_1B_xup_and2_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_2_1 || ORIG_REF_NAME==full_add_1B_xup_and2_2_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_or3_0_1/full_add_1B_xup_or3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_or3_0_1 || ORIG_REF_NAME==full_add_1B_xup_or3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_xor2_0_1/full_add_1B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_0_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_xor2_1_1/full_add_1B_xup_xor2_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_xor2_1_1 || ORIG_REF_NAME==full_add_1B_xup_xor2_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_xup_and2_0_2/full_add_1B_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_add_1B_xup_and2_0_2 || ORIG_REF_NAME==full_add_1B_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_nor4_0_0/full_adder_4B_xup_nor4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_nor4_0_0 || ORIG_REF_NAME==full_adder_4B_xup_nor4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_0/full_adder_4B_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_0 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_1/full_adder_4B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_1 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_2/full_adder_4B_xup_xor2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_2 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_0_3/full_adder_4B_xup_xor2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_0_3 || ORIG_REF_NAME==full_adder_4B_xup_xor2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ATAD_SPLIT_4_0_0/full_adder_4B_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ATAD_SPLIT_4_0_1/full_adder_4B_ATAD_SPLIT_4_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_1 || ORIG_REF_NAME==full_adder_4B_ATAD_SPLIT_4_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xlconcat_0_0/full_adder_4B_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xlconcat_0_0 || ORIG_REF_NAME==full_adder_4B_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_xup_xor2_4_0/full_adder_4B_xup_xor2_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==full_adder_4B_xup_xor2_4_0 || ORIG_REF_NAME==full_adder_4B_xup_xor2_4_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mini_UAL_full_adder_4B_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_ooc.xdc
