# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/mini_UAL_MIROIR_5B_0_0.xci
# IP: The module: 'mini_UAL_MIROIR_5B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_0/MIROIR_5B_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_0 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_1/MIROIR_5B_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_2/MIROIR_5B_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_2 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_3/MIROIR_5B_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_3 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_4/MIROIR_5B_xup_xor2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_4 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_4} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_0/MIROIR_5B_ATAD_SPLIT_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_0 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_1/MIROIR_5B_ATAD_SPLIT_5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_1 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_nor5_0_0/MIROIR_5B_xup_nor5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_nor5_0_0 || ORIG_REF_NAME==MIROIR_5B_xup_nor5_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xlconcat_0_0/MIROIR_5B_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xlconcat_0_0 || ORIG_REF_NAME==MIROIR_5B_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_5/MIROIR_5B_xup_xor2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_5 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_5} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_2/MIROIR_5B_ATAD_SPLIT_5_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_1_0/MIROIR_5B_ATAD_SPLIT_5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_nor5_0_1/MIROIR_5B_xup_nor5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_nor5_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_nor5_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xlconcat_0_1/MIROIR_5B_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xlconcat_0_1 || ORIG_REF_NAME==MIROIR_5B_xlconcat_0_1} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mini_UAL_MIROIR_5B_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/mini_UAL_MIROIR_5B_0_0.xci
# IP: The module: 'mini_UAL_MIROIR_5B_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_0/MIROIR_5B_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_0 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_1/MIROIR_5B_xup_xor2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_2/MIROIR_5B_xup_xor2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_2 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_3/MIROIR_5B_xup_xor2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_3 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_4/MIROIR_5B_xup_xor2_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_4 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_4} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_0/MIROIR_5B_ATAD_SPLIT_5_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_0 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_1/MIROIR_5B_ATAD_SPLIT_5_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_1 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_nor5_0_0/MIROIR_5B_xup_nor5_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_nor5_0_0 || ORIG_REF_NAME==MIROIR_5B_xup_nor5_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xlconcat_0_0/MIROIR_5B_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xlconcat_0_0 || ORIG_REF_NAME==MIROIR_5B_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_xor2_0_5/MIROIR_5B_xup_xor2_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_5 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_5} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_0_2/MIROIR_5B_ATAD_SPLIT_5_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ATAD_SPLIT_5_1_0/MIROIR_5B_ATAD_SPLIT_5_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xup_nor5_0_1/MIROIR_5B_xup_nor5_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_nor5_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_nor5_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_xlconcat_0_1/MIROIR_5B_xlconcat_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xlconcat_0_1 || ORIG_REF_NAME==MIROIR_5B_xlconcat_0_1} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mini_UAL_MIROIR_5B_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
