# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/Code_Conversion_MUX_2_vers_1_4bits_0_0.xci
# IP: The module: 'Code_Conversion_MUX_2_vers_1_4bits_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/MUX_2_vers_1_4bits_MUX_1B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/MUX_2_vers_1_4bits_MUX_1B_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_1 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/MUX_2_vers_1_4bits_MUX_1B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/MUX_2_vers_1_4bits_MUX_1B_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_1 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_xlconstant_0_0/MUX_2_vers_1_4bits_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_xlconstant_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_xlconstant_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_xlconcat_0_0/MUX_2_vers_1_4bits_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_xlconcat_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0/MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0/MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_MUX_2_vers_1_4bits_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/Code_Conversion_MUX_2_vers_1_4bits_0_0.xci
# IP: The module: 'Code_Conversion_MUX_2_vers_1_4bits_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/MUX_2_vers_1_4bits_MUX_1B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/MUX_2_vers_1_4bits_MUX_1B_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_1 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/MUX_2_vers_1_4bits_MUX_1B_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/MUX_2_vers_1_4bits_MUX_1B_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_1 || ORIG_REF_NAME==MUX_2_vers_1_4bits_MUX_1B_1_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_0/MUX_1B_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_0 || ORIG_REF_NAME==MUX_1B_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_inv_0_0/MUX_1B_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_0 || ORIG_REF_NAME==MUX_1B_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_inv_0_1/MUX_1B_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_inv_0_1 || ORIG_REF_NAME==MUX_1B_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_1/MUX_1B_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_1 || ORIG_REF_NAME==MUX_1B_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_2/MUX_1B_xup_and3_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_2 || ORIG_REF_NAME==MUX_1B_xup_and3_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_and3_0_3/MUX_1B_xup_and3_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_and3_0_3 || ORIG_REF_NAME==MUX_1B_xup_and3_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_xup_or4_0_0/MUX_1B_xup_or4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_1B_xup_or4_0_0 || ORIG_REF_NAME==MUX_1B_xup_or4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_xlconstant_0_0/MUX_2_vers_1_4bits_xlconstant_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_xlconstant_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_xlconstant_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_xlconcat_0_0/MUX_2_vers_1_4bits_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_xlconcat_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0/MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0/MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0 || ORIG_REF_NAME==MUX_2_vers_1_4bits_ATAD_SPLIT_4_1_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_ooc.xdc

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_MUX_2_vers_1_4bits_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
