# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: LABO3.xdc

# Block Designs: bd/Code_Conversion/Code_Conversion.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion || ORIG_REF_NAME==Code_Conversion} -quiet] -quiet

# IP: bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/Code_Conversion_code_Gray_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion_code_Gray_0_0 || ORIG_REF_NAME==Code_Conversion_code_Gray_0_0} -quiet] -quiet

# IP: bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/Code_Conversion_Code_secret_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion_Code_secret_0_0 || ORIG_REF_NAME==Code_Conversion_Code_secret_0_0} -quiet] -quiet

# IP: bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/Code_Conversion_MUX_2_vers_1_4bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion_MUX_2_vers_1_4bits_0_0 || ORIG_REF_NAME==Code_Conversion_MUX_2_vers_1_4bits_0_0} -quiet] -quiet

# IP: bd/Code_Conversion/ip/Code_Conversion_ATAD_SPLIT_4_0_0/Code_Conversion_ATAD_SPLIT_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion_ATAD_SPLIT_4_0_0 || ORIG_REF_NAME==Code_Conversion_ATAD_SPLIT_4_0_0} -quiet] -quiet

# IP: bd/Code_Conversion/ip/Code_Conversion_xlconcat_0_0/Code_Conversion_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_Conversion_xlconcat_0_0 || ORIG_REF_NAME==Code_Conversion_xlconcat_0_0} -quiet] -quiet

# XDC: bd/Code_Conversion/Code_Conversion_ooc.xdc
