# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab2.xdc

# Block Designs: bd/MIROIR_5B/MIROIR_5B.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B || ORIG_REF_NAME==MIROIR_5B} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_xor2_0_1/MIROIR_5B_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_1} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_xor2_0_2/MIROIR_5B_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_2 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_2} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_xor2_0_3/MIROIR_5B_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_3 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_3} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_xor2_0_4/MIROIR_5B_xup_xor2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_4 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_4} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_xor2_0_5/MIROIR_5B_xup_xor2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_xor2_0_5 || ORIG_REF_NAME==MIROIR_5B_xup_xor2_0_5} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_ATAD_SPLIT_5_0_2/MIROIR_5B_ATAD_SPLIT_5_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_0_2} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_ATAD_SPLIT_5_1_0/MIROIR_5B_ATAD_SPLIT_5_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0 || ORIG_REF_NAME==MIROIR_5B_ATAD_SPLIT_5_1_0} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xup_nor5_0_1/MIROIR_5B_xup_nor5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xup_nor5_0_1 || ORIG_REF_NAME==MIROIR_5B_xup_nor5_0_1} -quiet] -quiet

# IP: bd/MIROIR_5B/ip/MIROIR_5B_xlconcat_0_1/MIROIR_5B_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MIROIR_5B_xlconcat_0_1 || ORIG_REF_NAME==MIROIR_5B_xlconcat_0_1} -quiet] -quiet

# XDC: bd/MIROIR_5B/MIROIR_5B_ooc.xdc
