# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/Code_Conversion_Code_secret_0_0.xci
# IP: The module: 'Code_Conversion_Code_secret_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and3_0_0/Code_secret_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and3_0_0 || ORIG_REF_NAME==Code_secret_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_0/Code_secret_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_0 || ORIG_REF_NAME==Code_secret_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_1/Code_secret_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_1 || ORIG_REF_NAME==Code_secret_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_2/Code_secret_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_2 || ORIG_REF_NAME==Code_secret_xup_inv_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and3_0_1/Code_secret_xup_and3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and3_0_1 || ORIG_REF_NAME==Code_secret_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and2_0_0/Code_secret_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and2_0_0 || ORIG_REF_NAME==Code_secret_xup_and2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and2_0_1/Code_secret_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and2_0_1 || ORIG_REF_NAME==Code_secret_xup_and2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_ATAD_SPLIT_3_0_0/Code_secret_ATAD_SPLIT_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_ATAD_SPLIT_3_0_0 || ORIG_REF_NAME==Code_secret_ATAD_SPLIT_3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xlconcat_0_0/Code_secret_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xlconcat_0_0 || ORIG_REF_NAME==Code_secret_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_Code_secret_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/Code_Conversion_Code_secret_0_0.xci
# IP: The module: 'Code_Conversion_Code_secret_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and3_0_0/Code_secret_xup_and3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and3_0_0 || ORIG_REF_NAME==Code_secret_xup_and3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_0/Code_secret_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_0 || ORIG_REF_NAME==Code_secret_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_1/Code_secret_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_1 || ORIG_REF_NAME==Code_secret_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_inv_0_2/Code_secret_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_inv_0_2 || ORIG_REF_NAME==Code_secret_xup_inv_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and3_0_1/Code_secret_xup_and3_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and3_0_1 || ORIG_REF_NAME==Code_secret_xup_and3_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and2_0_0/Code_secret_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and2_0_0 || ORIG_REF_NAME==Code_secret_xup_and2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xup_and2_0_1/Code_secret_xup_and2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xup_and2_0_1 || ORIG_REF_NAME==Code_secret_xup_and2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_ATAD_SPLIT_3_0_0/Code_secret_ATAD_SPLIT_3_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_ATAD_SPLIT_3_0_0 || ORIG_REF_NAME==Code_secret_ATAD_SPLIT_3_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_xlconcat_0_0/Code_secret_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Code_secret_xlconcat_0_0 || ORIG_REF_NAME==Code_secret_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_Code_secret_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
