# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.cache/wt [current_project]
set_property parent.project_path D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/Users/Nathan/Documents/INF1500/Labo/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/hdl/Code_Conversion_wrapper.vhd
add_files D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/Code_Conversion.bd
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_Code_secret_0_0/src/Code_secret_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_0/src/MUX_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_0_1/src/MUX_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_0/src/MUX_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_MUX_1B_1_1/src/MUX_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_MUX_2_vers_1_4bits_0_0/src/MUX_2_vers_1_4bits_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/Code_Conversion_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/constrs_1/LABO3.xdc
set_property used_in_implementation false [get_files D:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/constrs_1/LABO3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Code_Conversion_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Code_Conversion_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Code_Conversion_wrapper_utilization_synth.rpt -pb Code_Conversion_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
