@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Oct 21 14:27:43 -0400 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim MUX_1B_wrapper_behav -key {Behavioral:sim_1:Functional:MUX_1B_wrapper} -tclbatch MUX_1B_wrapper.tcl -protoinst "protoinst_files/MIROIR_5B.protoinst" -protoinst "protoinst_files/mini_UAL.protoinst" -protoinst "protoinst_files/DIV_4_5B.protoinst" -protoinst "protoinst_files/MUX_1B.protoinst" -protoinst "protoinst_files/MUX_5B.protoinst" -log simulate.log"
call xsim  MUX_1B_wrapper_behav -key {Behavioral:sim_1:Functional:MUX_1B_wrapper} -tclbatch MUX_1B_wrapper.tcl -protoinst "protoinst_files/MIROIR_5B.protoinst" -protoinst "protoinst_files/mini_UAL.protoinst" -protoinst "protoinst_files/DIV_4_5B.protoinst" -protoinst "protoinst_files/MUX_1B.protoinst" -protoinst "protoinst_files/MUX_5B.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
