# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/Code_Conversion_code_Gray_0_0.xci
# IP: The module: 'Code_Conversion_code_Gray_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_0/code_Gray_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_0 || ORIG_REF_NAME==code_Gray_xup_and2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_0/code_Gray_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_0 || ORIG_REF_NAME==code_Gray_xup_or2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_3/code_Gray_xup_or2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_3 || ORIG_REF_NAME==code_Gray_xup_or2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_0/code_Gray_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_0 || ORIG_REF_NAME==code_Gray_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_1/code_Gray_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_1 || ORIG_REF_NAME==code_Gray_xup_and2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_1/code_Gray_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_1 || ORIG_REF_NAME==code_Gray_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_2/code_Gray_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_2 || ORIG_REF_NAME==code_Gray_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_1_0/code_Gray_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_1_0 || ORIG_REF_NAME==code_Gray_xup_inv_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_2_0/code_Gray_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_2_0 || ORIG_REF_NAME==code_Gray_xup_and2_2_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_3_0/code_Gray_xup_or2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_3_0 || ORIG_REF_NAME==code_Gray_xup_or2_3_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_3_0/code_Gray_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_3_0 || ORIG_REF_NAME==code_Gray_xup_and2_3_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xlconcat_0_0/code_Gray_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xlconcat_0_0 || ORIG_REF_NAME==code_Gray_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_3/code_Gray_xup_and2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_3 || ORIG_REF_NAME==code_Gray_xup_and2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_2/code_Gray_xup_or2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_2 || ORIG_REF_NAME==code_Gray_xup_or2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_2/code_Gray_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_2 || ORIG_REF_NAME==code_Gray_xup_inv_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_5_0/code_Gray_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_5_0 || ORIG_REF_NAME==code_Gray_xup_and2_5_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_code_Gray_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/Code_Conversion_code_Gray_0_0.xci
# IP: The module: 'Code_Conversion_code_Gray_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_0/code_Gray_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_0 || ORIG_REF_NAME==code_Gray_xup_and2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_0/code_Gray_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_0 || ORIG_REF_NAME==code_Gray_xup_or2_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_3/code_Gray_xup_or2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_3 || ORIG_REF_NAME==code_Gray_xup_or2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_0/code_Gray_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_0 || ORIG_REF_NAME==code_Gray_xup_inv_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_1/code_Gray_xup_and2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_1 || ORIG_REF_NAME==code_Gray_xup_and2_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_1/code_Gray_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_1 || ORIG_REF_NAME==code_Gray_xup_inv_0_1} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_2/code_Gray_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_2 || ORIG_REF_NAME==code_Gray_xup_and2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_1_0/code_Gray_xup_inv_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_1_0 || ORIG_REF_NAME==code_Gray_xup_inv_1_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_2_0/code_Gray_xup_and2_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_2_0 || ORIG_REF_NAME==code_Gray_xup_and2_2_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_3_0/code_Gray_xup_or2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_3_0 || ORIG_REF_NAME==code_Gray_xup_or2_3_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_3_0/code_Gray_xup_and2_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_3_0 || ORIG_REF_NAME==code_Gray_xup_and2_3_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xlconcat_0_0/code_Gray_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xlconcat_0_0 || ORIG_REF_NAME==code_Gray_xlconcat_0_0} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_0_3/code_Gray_xup_and2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_0_3 || ORIG_REF_NAME==code_Gray_xup_and2_0_3} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_or2_0_2/code_Gray_xup_or2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_or2_0_2 || ORIG_REF_NAME==code_Gray_xup_or2_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_inv_0_2/code_Gray_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_inv_0_2 || ORIG_REF_NAME==code_Gray_xup_inv_0_2} -quiet] -quiet

# IP: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_xup_and2_5_0/code_Gray_xup_and2_5_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==code_Gray_xup_and2_5_0 || ORIG_REF_NAME==code_Gray_xup_and2_5_0} -quiet] -quiet

# XDC: d:/Users/Nathan/Documents/INF1500/Labo/project_3/project_3.srcs/sources_1/bd/Code_Conversion/ip/Code_Conversion_code_Gray_0_0/src/code_Gray_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Code_Conversion_code_Gray_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
