# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab2.xdc

# Block Designs: bd/mini_UAL/mini_UAL.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL || ORIG_REF_NAME==mini_UAL} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xup_xor2_0_0/mini_UAL_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xup_xor2_0_0 || ORIG_REF_NAME==mini_UAL_xup_xor2_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xlconcat_0_0/mini_UAL_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xlconcat_0_0 || ORIG_REF_NAME==mini_UAL_xlconcat_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xlconcat_0_1/mini_UAL_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xlconcat_0_1 || ORIG_REF_NAME==mini_UAL_xlconcat_0_1} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xlconcat_2_0/mini_UAL_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xlconcat_2_0 || ORIG_REF_NAME==mini_UAL_xlconcat_2_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xlconcat_2_1/mini_UAL_xlconcat_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xlconcat_2_1 || ORIG_REF_NAME==mini_UAL_xlconcat_2_1} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_ATAD_SPLIT_5_0_0/mini_UAL_ATAD_SPLIT_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_ATAD_SPLIT_5_0_0 || ORIG_REF_NAME==mini_UAL_ATAD_SPLIT_5_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_ATAD_SPLIT_5_0_1/mini_UAL_ATAD_SPLIT_5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_ATAD_SPLIT_5_0_1 || ORIG_REF_NAME==mini_UAL_ATAD_SPLIT_5_0_1} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/mini_UAL_MIROIR_5B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_MIROIR_5B_0_0 || ORIG_REF_NAME==mini_UAL_MIROIR_5B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_DIV_4_5B_0_0/mini_UAL_DIV_4_5B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_DIV_4_5B_0_0 || ORIG_REF_NAME==mini_UAL_DIV_4_5B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_xlconcat_3_0/mini_UAL_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_xlconcat_3_0 || ORIG_REF_NAME==mini_UAL_xlconcat_3_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/mini_UAL_full_adder_4B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_full_adder_4B_0_0 || ORIG_REF_NAME==mini_UAL_full_adder_4B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_DIV_4_5B_0_0_1/mini_UAL_DIV_4_5B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_DIV_4_5B_0_0 || ORIG_REF_NAME==mini_UAL_DIV_4_5B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_MUX_5B_0_0/mini_UAL_MUX_5B_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_MUX_5B_0_0 || ORIG_REF_NAME==mini_UAL_MUX_5B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_MUX_5B_0_0_1/mini_UAL_MUX_5B_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_MUX_5B_0_0 || ORIG_REF_NAME==mini_UAL_MUX_5B_0_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_MUX_5B_1_0/mini_UAL_MUX_5B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_MUX_5B_1_0 || ORIG_REF_NAME==mini_UAL_MUX_5B_1_0} -quiet] -quiet

# IP: bd/mini_UAL/ip/mini_UAL_DIV_4_5B_1_0/mini_UAL_DIV_4_5B_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mini_UAL_DIV_4_5B_1_0 || ORIG_REF_NAME==mini_UAL_DIV_4_5B_1_0} -quiet] -quiet

# XDC: bd/mini_UAL/mini_UAL_ooc.xdc
