# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {IP_Flow 19-3664}  -suppress 
set_msg_config  -id {Synth 8-3331}  -suppress 
set_msg_config  -id {filemgmt 20-645}  -suppress 
set_msg_config  -id {Project 1-498}  -string {{WARNING: [Project 1-498] One or more constraints failed evaluation while reading constraint file [D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/constrs_1/new/lab2.xdc] and the design contains unresolved black boxes. These constraints will be read post-synthesis (as long as their source constraint file is marked as used_in_implementation) and should be applied correctly then. You should review the constraints listed in the file [.Xil/MIROIR_5B_wrapper_propImpl.xdc] and check the run log file to verify that these constraints were correctly applied.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.cache/wt [current_project]
set_property parent.project_path D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Users/Nathan/Documents/INF1500/Labo/ip_repo [current_project]
update_ip_catalog
set_property ip_output_repo d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/hdl/mini_UAL_wrapper.v
add_files D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/mini_UAL.bd
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_MIROIR_5B_0_0/src/MIROIR_5B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_0_0/src/full_add_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_0/src/full_add_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_1/src/full_add_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_full_adder_4B_0_0/src/full_adder_4B_full_add_1B_1_2/src/full_add_1B_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/ip/mini_UAL_DIV_4_5B_1_0/src/DIV_4_5B_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/sources_1/bd/mini_UAL/mini_UAL_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/constrs_1/new/lab2.xdc
set_property used_in_implementation false [get_files D:/Users/Nathan/Documents/INF1500/Labo/project_2/project_2.srcs/constrs_1/new/lab2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mini_UAL_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mini_UAL_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mini_UAL_wrapper_utilization_synth.rpt -pb mini_UAL_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
